<?php

declare(strict_types=1);

namespace Core\Console\Commands;

/**
 * Compile all config files into a single cached PHP file.
 *
 * Usage: php myth config:cache
 *
 * Bootstrap picks up the cache automatically when ENVIRONMENT=production.
 * Run this after every deployment to avoid per-request config I/O.
 *
 */
final class ConfigCacheCommand
{
    public function handle(): void
    {
        if (!function_exists('loadConfig')) {
            throw new \RuntimeException(
                'loadConfig() is not available. Run this command after bootstrap.'
            );
        }

        echo "Building config cache...\n";

        $config    = loadConfig([]);
        $cacheDir  = ROOT_DIR . 'storage/cache/';
        $cacheFile = $cacheDir . 'config.cache.php';

        if (!is_dir($cacheDir) && !mkdir($cacheDir, 0750, true) && !is_dir($cacheDir)) {
            throw new \RuntimeException("Failed to create cache directory: {$cacheDir}");
        }

        $content = '<?php' . PHP_EOL
            . '// Generated by: php myth config:cache' . PHP_EOL
            . '// At: ' . date('Y-m-d H:i:s T') . PHP_EOL
            . '// Delete with: php myth config:clear' . PHP_EOL
            . 'return ' . var_export($config, true) . ';' . PHP_EOL;

        if (file_put_contents($cacheFile, $content, LOCK_EX) === false) {
            throw new \RuntimeException("Failed to write config cache: {$cacheFile}");
        }

        echo "Configuration cached successfully → {$cacheFile}\n";
        echo 'Keys cached: ' . implode(', ', array_keys($config)) . PHP_EOL;
    }
}
