<?php

declare(strict_types=1);

namespace Core\Console\Commands;

/**
 * Compile all registered routes into a single cached PHP file.
 *
 * Usage: php myth route:cache
 *
 * Routes are always loaded fresh from app/routes/web.php and app/routes/api.php
 * via RouteServiceProvider so that middleware groups (web, api) are applied
 * identically to a normal HTTP request. Any existing cache is deleted first so
 * re-running the command always reflects the current route files.
 *
 * Routes whose action is a Closure cannot be serialised and are skipped with a
 * warning. Convert them to [ControllerClass::class, 'method'] to cache them.
 */
final class RouteCacheCommand
{
    public function handle(): void
    {
        echo "Building route cache...\n";

        $cacheDir  = ROOT_DIR . 'storage/cache/';
        $cacheFile = $cacheDir . 'routes.cache.php';

        // Step 1: Delete the existing cache first so RouteServiceProvider will
        // load fresh from route files, not from the stale cache.
        if (is_file($cacheFile) && !@unlink($cacheFile)) {
            throw new \RuntimeException("Cannot delete existing route cache: {$cacheFile}");
        }

        // Step 2: Build a fresh router with the identical middleware configuration
        // used by the HTTP Kernel on every real request.
        $frameworkConfig = (array) (config('framework') ?? []);
        $router = new \Core\Routing\Router();
        $router->aliasMiddleware((array) ($frameworkConfig['middleware_aliases'] ?? []));
        $router->middlewareGroup((array) ($frameworkConfig['middleware_groups'] ?? []));

        // Step 3: Load routes through RouteServiceProvider.
        // This applies the 'web' and 'api' middleware groups exactly as a real request would.
        $routeProvider = new \Core\Routing\RouteServiceProvider($frameworkConfig);
        $routeProvider->mapWeb($router);
        $routeProvider->mapApi($router);

        // Expose the instance for any post-registration hooks or tools.
        \Core\Routing\Router::setInstance($router);

        // Step 4: Export the compiled route index to a PHP cache file.
        $data = $router->getCompiledRoutes();

        if (!is_dir($cacheDir) && !mkdir($cacheDir, 0750, true) && !is_dir($cacheDir)) {
            throw new \RuntimeException("Failed to create cache directory: {$cacheDir}");
        }

        $staticCount  = count($data['static']);
        $dynamicCount = array_sum(array_map('count', $data['dynamic']));
        $total        = $staticCount + $dynamicCount;
        $skipped      = (int) $data['skipped'];

        $content = '<?php' . PHP_EOL
            . '// Generated by: php myth route:cache' . PHP_EOL
            . '// At: ' . date('Y-m-d H:i:s T') . PHP_EOL
            . '// Routes: ' . $total . ' cached, ' . $skipped . ' closure(s) skipped' . PHP_EOL
            . '// Clear with: php myth route:clear' . PHP_EOL
            . 'return ' . var_export($data, true) . ';' . PHP_EOL;

        if (file_put_contents($cacheFile, $content, LOCK_EX) === false) {
            throw new \RuntimeException("Failed to write route cache: {$cacheFile}");
        }

        // Invalidate OPcache for the newly written file so all workers pick it up immediately.
        if (function_exists('opcache_invalidate')) {
            opcache_invalidate($cacheFile, true);
        }

        echo "Route cache written → {$cacheFile}\n";
        echo "  Static routes:  {$staticCount}\n";
        echo "  Dynamic routes: {$dynamicCount}\n";

        if ($skipped > 0) {
            echo "  WARNING: {$skipped} closure-based route(s) were skipped.\n";
            echo "  Convert them to [ControllerClass::class, 'method'] to include them in the cache.\n";
        }
    }
}
