<?php

declare(strict_types=1);

namespace Core\Console\Commands;

/**
 * Compile all registered routes into a single cached PHP file.
 *
 * Usage: php myth route:cache
 *
 * Enables O(1) route lookups in production by skipping route file parsing
 * on every request.
 *
 */
final class RouteCacheCommand
{
    public function handle(): void
    {
        echo "Building route cache...\n";

        // Load route files to register all routes
        $webRoutes = ROOT_DIR . 'app/routes/web.php';
        $apiRoutes = ROOT_DIR . 'app/routes/api.php';

        if (is_file($webRoutes)) {
            require_once $webRoutes;
        }

        if (is_file($apiRoutes)) {
            require_once $apiRoutes;
        }

        // Resolve router instance — try common class names used in the framework
        $router = null;
        foreach ([
            \Core\Routing\Router::class,
            \Core\Router\Router::class,
        ] as $routerClass) {
            if (class_exists($routerClass) && method_exists($routerClass, 'getInstance')) {
                $instance = $routerClass::getInstance();
                if (method_exists($instance, 'getCompiledRoutes')) {
                    $router = $instance;
                    break;
                }
            }
        }

        if ($router === null) {
            throw new \RuntimeException(
                'Router not found or does not implement getCompiledRoutes(). '
                . 'Add getCompiledRoutes() to your Router class.'
            );
        }

        $routes    = $router->getCompiledRoutes();
        $cacheDir  = ROOT_DIR . 'storage/cache/';
        $cacheFile = $cacheDir . 'routes.cache.php';

        if (!is_dir($cacheDir) && !mkdir($cacheDir, 0750, true) && !is_dir($cacheDir)) {
            throw new \RuntimeException("Failed to create cache directory: {$cacheDir}");
        }

        $content = '<?php' . PHP_EOL
            . '// Generated by: php myth route:cache' . PHP_EOL
            . '// At: ' . date('Y-m-d H:i:s T') . PHP_EOL
            . '// Delete with: php myth route:clear' . PHP_EOL
            . 'return ' . var_export($routes, true) . ';' . PHP_EOL;

        if (file_put_contents($cacheFile, $content, LOCK_EX) === false) {
            throw new \RuntimeException("Failed to write route cache: {$cacheFile}");
        }

        $count = count($routes);
        echo "Routes cached successfully → {$cacheFile} ({$count} routes)\n";
    }
}
